graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "A"
      graphics [
         x 335
         y 176
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 523
         y 165
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 538
         y 279
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 359
         y 300
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 545
         y 365
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 353
         y 387
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 3
      label ""
      weight 1.0
   ]
]