graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 482
         y 245
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 605
         y 251
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 732
         y 261
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 856
         y 259
      ]
   ]
   node [
      id 4
      label "A"
      graphics [
         x 860
         y 353
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 738
         y 353
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 609
         y 345
      ]
   ]
   node [
      id 10
      label "N"
      graphics [
         x 468
         y 345
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 466
         y 441
      ]
   ]
   node [
      id 12
      label "N"
      graphics [
         x 605
         y 442
      ]
   ]
   node [
      id 13
      label "N"
      graphics [
         x 742
         y 444
      ]
   ]
   node [
      id 14
      label "N"
      graphics [
         x 871
         y 441
      ]
   ]
   node [
      id 15
      label "N"
      graphics [
         x 871
         y 531
      ]
   ]
   node [
      id 16
      label "N"
      graphics [
         x 739
         y 532
      ]
   ]
   node [
      id 17
      label "N"
      graphics [
         x 614
         y 537
      ]
   ]
   node [
      id 18
      label "N"
      graphics [
         x 473
         y 541
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 10
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 11
      target 12
      label ""
      weight 1.0
   ]
   edge [
      source 12
      target 13
      label ""
      weight 1.0
   ]
   edge [
      source 13
      target 14
      label ""
      weight 1.0
   ]
   edge [
      source 14
      target 15
      label ""
      weight 1.0
   ]
   edge [
      source 15
      target 16
      label ""
      weight 1.0
   ]
   edge [
      source 16
      target 17
      label ""
      weight 1.0
   ]
   edge [
      source 17
      target 18
      label ""
      weight 1.0
   ]
   edge [
      source 18
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 12
      target 17
      label ""
      weight 1.0
   ]
   edge [
      source 13
      target 16
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 14
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 13
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 12
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 10
      label ""
      weight 1.0
   ]
]