graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 377
         y 215
      ]
   ]
   node [
      id 1
      label "A"
      graphics [
         x 532
         y 217
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 701
         y 217
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 701
         y 383
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 701
         y 554
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 536
         y 554
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 379
         y 554
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 379
         y 386
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 536
         y 386
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 5
      label ""
      weight 1.0
   ]
]