graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 412
         y 158
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 559
         y 253
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 687
         y 160
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 365
         y 316
      ]
   ]
   node [
      id 4
      label "N"
      graphics [
         x 553
         y 358
      ]
   ]
   node [
      id 5
      label "N"
      graphics [
         x 707
         y 314
      ]
   ]
   node [
      id 6
      label "N"
      graphics [
         x 591
         y 453
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 562
         y 557
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 659
         y 416
      ]
   ]
   node [
      id 11
      label "N"
      graphics [
         x 654
         y 521
      ]
   ]
   node [
      id 12
      label "N"
      graphics [
         x 436
         y 546
      ]
   ]
   node [
      id 13
      label "N"
      graphics [
         x 500
         y 616
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 12
      label ""
      weight 1.0
   ]
   edge [
      source 12
      target 13
      label ""
      weight 1.0
   ]
]