graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "N"
      graphics [
         x 557
         y 296
      ]
   ]
   node [
      id 1
      label "N"
      graphics [
         x 462
         y 206
      ]
   ]
   node [
      id 2
      label "N"
      graphics [
         x 689
         y 186
      ]
   ]
   node [
      id 3
      label "N"
      graphics [
         x 604
         y 396
      ]
   ]
   node [
      id 7
      label "N"
      graphics [
         x 544
         y 506
      ]
   ]
   node [
      id 8
      label "N"
      graphics [
         x 489
         y 346
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 8
      label ""
      weight 1.0
   ]
]